/* This file was generated by a make rule */
#define MUST_BUILD_WININET_CLIENT 0
#define MUST_BUILD_CURL_CLIENT 0
#define MUST_BUILD_LIBWWW_CLIENT 1
static const char * const XMLRPC_DEFAULT_TRANSPORT =
"libwww";
